Spring:
  application:
    name: BlogAPI
  datasource:
    url: jdbc:mysql://localhost:3306/blog_db
    username: root
    password: Olotu1234_
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
